name: shelf_letsencrypt
description: Let's Encrypt support for the shelf package (free and automatic HTTPS certificate support).
version: 1.2.1
homepage: https://github.com/gmpassos/shelf_letsencrypt

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.3
  shelf: ^1.4.1
  acme_client: ^1.2.0
  basic_utils: ^5.6.1
  coverage: ^1.6.3
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
  dependency_validator: ^3.2.2
