name: shelf_letsencrypt
version: 2.0.0
homepage: https://github.com/gmpassos/shelf_letsencrypt
publish_to: https://onepub.dev/api/jbbxpsdavu/
description: Let's Encrypt support for the shelf package (free and automatic HTTPS certificate support).
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  acme_client: ^1.2.0
  basic_utils: ^5.6.1
  collection: ^1.18.0
  coverage: ^1.6.3
  path: ^1.8.3
  shelf: ^1.4.1
dev_dependencies: 
  dependency_validator: ^3.2.2
  lints: ^3.0.0
  test: ^1.24.6
