name: shelf_letsencrypt
version: 2.0.0-beta.4
homepage: https://github.com/gmpassos/shelf_letsencrypt
description: Let's Encrypt support for the shelf package (free and automatic HTTPS certificate support).

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  acme_client: ^1.3.0
  basic_utils: ^5.7.0
  collection: ^1.18.0
  multi_domain_secure_server: ^1.0.6
  path: ^1.9.1
  shelf: ^1.4.2

dev_dependencies:
  cron: ^0.5.1
  dependency_validator: ^4.1.1
  coverage: ^1.11.0
  lints: ^3.0.0
  test: ^1.25.9

#dependency_overrides:
#  multi_domain_secure_server:
#    path: ../multi_domain_secure_server
#
